---
title: "Untitled"
output:
  html_document:
    fig_caption: yes
    fig_width: 5
    highlight: pygments
    number_sections: yes
    theme: spacelab
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r require,message=FALSE}
setwd('/mnt/raid61/Personal_data/xiaoxia/APA/Project/Hema_mouse/3seq/analysis')
suppressPackageStartupMessages({
  library("DESeq2")
  library("RColorBrewer")
  library("pheatmap")
  library("factoextra")
  library("FactoMineR")
  library("cluster")
  library(data.table)
  library(dplyr)
  library(ggsci)
  library(scales)
  library(parallel)
  library(dplyr)
  library(plyr)
  library(VGAM)
})
```

```{r , warning=FALSE, message=FALSE}
APAdata <- readRDS('../quantifyPA/all.pa/PA.Expr.filter.rds')
pa.anno <- fread('../PAfeatures/all.pa.annotated.uniqued.txt')
sample.info <- fread('../sample.info.txt')
```

```{r Analysis APAcounts, warning=FALSE, message=FALSE}
countsdata <- as.matrix(APAdata[,-1])
rownames(countsdata) <- APAdata$PA.grouped
colnames(countsdata) <- gsub('.all.txt','',colnames(APAdata)[-1])
countsdata[is.na(countsdata)] <- 0
coldata <- sample.info[match(colnames(countsdata),sample.info$Run),]
rownames(coldata) <- coldata$Run
#subset genes has more than one PA site
names(table(pa.anno$gene_id)[table(pa.anno$gene_id)>1])->apa_gene
use.pa <- pa.anno[gene_id%in%apa_gene,]$PA
countsdata <- countsdata[rownames(countsdata)%in%use.pa,]
dds <- DESeqDataSetFromMatrix(countData = countsdata,
                              colData = coldata,
                              design = ~ CellType)
saveRDS(dds,file='rawdata/APA.gene.withreplicates.rds')
```


```{r bulk counts}
#
bulk.df <- list()
for(i in unique(dds$CellType)){
  samples <- as.character(colData(dds)[colData(dds)$CellType == i, ]$Run)
  df <- as.data.frame(assay(dds)[,samples])
  if(ncol(df) == 1 ){
    colnames(df) <- i
  }else{
    df <- as.data.frame(round(rowSums(df),0))
    colnames(df) <- i
  }
  bulk.df[[i]] <- df
}
bulk.df <- do.call(cbind, bulk.df)


Exprs.norep <- bulk.df
sample.info.new <- data.frame(CellType=colnames(Exprs.norep),
                              ColName=colnames(Exprs.norep))

rownames(sample.info.new) <- colnames(Exprs.norep)
dds <- DESeqDataSetFromMatrix(countData = Exprs.norep,
                              colData = sample.info.new,
                              design = ~ CellType)


saveRDS(dds,file='./rawdata/APA.gene.dds.rds')
ntd <- normTransform(dds)
saveRDS(ntd,file='./rawdata/APA_gene.ntd.rds')

ge<-t(assay(ntd))
res <- hcut(ge, k = 4, stand = T)
# Visualize
pdf('./figures/dendritic.pdf',6,6)
fviz_dend(res, rect = T, cex = 1,type = 'phylogenic',repel=T,
          k_colors = c("#00AFBB","#2E9FDF", "#E7B800", "#FC4E07"))
dev.off()
#pheatmap of kmeas
#df <- assay(ntd)
#df <-df[rowSums(df) < 20,]
#pheatmap(df, cluster_rows=FALSE, show_rownames=FALSE)

```

```{r randomfores}
dds <- readRDS('./analysis/rawdata/APA.gene.dds.rds')
ntd <- normTransform(dds)
x <- t(assay(ntd))
cl <- as.factor(res$cluster)
rf.vs <- varSelRF(x, cl, ntree=2000, ntreeIterat=1000, vars.drop.frac=0.3)

saveRDS(rf.vs,file='./rawdata/rf.vs.rds')
rf.res <- readRDS('rawdata/rf.vs.rds')

plot.data <- t(x)[rf.res$selected.vars,]

color =colorRampPalette(rev(brewer.pal(11,'Spectral')))(200)
p.z<- pheatmap(plot.data,cluster_cols = T,show_rownames = F,
color = color,
#cutree_rows=5,
scale = 'row'
)
p.n <- pheatmap(plot.data,cluster_cols = T,show_rownames = F,color = color)
pdf('./figures/heatmap_randomforest.zscore.pdf',8,6)
p.z
dev.off()
pdf('./figures/heatmap_randomforest.noscale.pdf',8,6)
p.n
dev.off()

pa.clust <- as.data.frame(cbind(plot.data,
  cluster = cutree(p.z$tree_row,
    k = 5)))

mature.cells <- rownames(pa.clust[pa.clust$cluster==2,])
lymphoid <- rownames(pa.clust[pa.clust$cluster==1,])
progenitors <- rownames(pa.clust[pa.clust$cluster==3,])
ery <- rownames(pa.clust[pa.clust$cluster==4,])
myloid <- rownames(pa.clust[pa.clust$cluster==5,])

#reoder the data frame
ordered.data <- plot.data[c(mature.cells,lymphoid,progenitors,ery,myloid),]
ano_row <- data.frame(row.names= rownames(ordered.data),
                      Lineage = c(rep('Mature', length(mature.cells)),
                                  rep('Lymphoid',length(lymphoid)),
                                  rep('Progenitors',length(progenitors)),
                                  rep('Erythroid',length(ery)),
                                  rep('Myeloid',length(myloid))))

pdf('./figures/heatmap_randomforest.labeled.pdf',8,6)
pheatmap(ordered.data,cluster_cols = T,show_rownames = F,
cluster_rows =F,color = color,scale = 'row',annotation_row = ano_row)
dev.off()
#specific gene and Pa type
pa.anno <- fread('../PAfeatures/all.pa.annotated.uniqued.txt')
use.pa <- c(mature.cells,lymphoid,progenitors,ery,myloid)
use.pa.anno <- pa.anno[match(rownames(ano_row),PA),]
use.pa.anno$Lineage <-ano_row$Lineage
save(use.pa.anno,file='rawdata/specific.pa.RData')


library(ggsci)

p.pa.type <- melt(use.pa.anno[,c('PA.type','Lineage')])%>%table%>%as.data.frame%>%
            ggplot(aes(Lineage,Freq,fill=PA.type))+
            geom_bar(position = 'dodge', stat='identity')+
            scale_fill_lancet()+
            geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25)+
            labs(y = 'Number of PAs')+
            theme(plot.title = element_text(hjust = 0.5,face = 'bold', size = 16),
                  legend.position = 'top', legend.title = element_blank(),
                  legend.text = element_text(size=15),
                  axis.text.x = element_text(size=15),
                  axis.title.x = element_blank(),
                  axis.title.y = element_text(size=15),
                  axis.text.y  = element_text(size=15),
                  panel.grid.major =element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.background = element_blank(),
                  axis.line = element_line(colour = "black"))
pdf('./figures/specific.PA.type.pdf',8,6)
p.pa.type
dev.off()
APA.colors = pal_nejm()(8)
gene.type <-melt(use.pa.anno[,c('gene_biotype','Lineage')])%>%table%>%as.data.frame%>%
            ggplot(aes(Lineage,Freq,fill=gene_biotype))+
            geom_bar(position = 'dodge', stat='identity')+
            scale_fill_manual(values = APA.colors[c(4,5,6)])+
            #geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25)+
            labs(y = 'Number of genes')+
            theme(plot.title = element_text(hjust = 0.5,face = 'bold', size = 16),
                  legend.position = 'top', legend.title = element_blank(),
                  legend.text = element_text(size=15),
                  axis.text.x = element_text(size=15),
                  axis.title.x = element_blank(),
                  axis.title.y = element_text(size=15),
                  axis.text.y  = element_text(size=15),
                  panel.grid.major =element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.background = element_blank(),
                  axis.line = element_line(colour = "black"))
pdf('./figures/specific.gene.type.pdf',8,6)
gene.type
dev.off()


#GO 
library(AnnotationDbi)
library(org.Mm.eg.db)
library(DOSE)
library(GO.db)
library(topGO)
library(GSEABase)
library(clusterProfiler)
library(Rgraphviz)
mature.gene <- use.pa.anno[Lineage == 'Mature',]$gene_id
progenitor.gene <- use.pa.anno[Lineage == 'Progenitors',]$gene_id
lymphoid.gene <- use.pa.anno[Lineage == 'Lymphoid',]$gene_id
erythroid.gene <- use.pa.anno[Lineage == 'Erythroid',]$gene_id
myeloid.gene <- use.pa.anno[Lineage == 'Myeloid',]$gene_id
PA.GO <- enrichGO(gene = use.pa.anno$gene_id,
                       OrgDb  = org.Mm.eg.db, keyType = "ENSEMBL",
                       ont  = "BP", pAdjustMethod = "BH",
                       pvalueCutoff  = 0.05,qvalueCutoff  = 0.2)
edox <- setReadable(PA.GO, 'org.Mm.eg.db', 'ENSEMBL')
p1 <- cnetplot(edox)
pdf('./figures/go.pdf',height=6, width=15)
heatplot(edox,showCategory = 20)
dev.off()


#
symbols <- use.pa.anno$gene_name
entrize_genes<-mapIds(org.Mm.eg.db, symbols, 'ENTREZID', 'SYMBOL')
entrize_genes <- entrize_genes[use.pa.anno$gene_name]
mydf <- data.frame(Entrez = as.numeric(entrize_genes),group = use.pa.anno$Lineage)
xx.formula <- compareCluster(Entrez~group, data=mydf,
                              OrgDb='org.Mm.eg.db',
                                  fun='enrichGO' )
dotplot(xx.formula)
dev.off()

PA.KEGG <- enrichKEGG(KEGG_genes,organism='mmu')
pdf(paste('GO_lineage.pdf'),height = 8,width = 10)
dotplot(PA.GO,showCategory = 20,font.size = 10)
dev.off()
enrichMap(PA.GO)
plotGOgraph(PA.GO,firstSigNodes = 15, useInfo = "all")
dev.off()

```




